import React, { useEffect, useMemo, useState } from 'react'
import { ChevronLeft, ChevronRight, CircleDollarSign, Plus, Trash2 } from 'lucide-react'
import { useTheme } from '../theme'

const stages = [{ id: 'novo', label: 'Novos' }, { id: 'qualificacao', label: 'Qualificação' }, { id: 'proposta', label: 'Proposta' }, { id: 'ganho', label: 'Ganhos' }]

export default function Pipeline({ accountId }: { accountId: string }) {
  const { colors } = useTheme(); const [deals, setDeals] = useState<any[]>([]); const [creating, setCreating] = useState(false)
  const [form, setForm] = useState({ title: '', phone: '', value: '', owner: '', notes: '' })
  const load = () => window.zap.getDeals(accountId).then(setDeals)
  useEffect(() => { void load() }, [accountId])
  const total = useMemo(() => deals.reduce((sum, deal) => sum + Number(deal.value || 0), 0), [deals])
  async function move(deal: any, offset: number) { const at = stages.findIndex(s => s.id === deal.stage); const next = stages[at + offset]; if (!next) return; await window.zap.saveDeal({ ...deal, stage: next.id }); await load() }
  async function create() { if (!form.title.trim() || !form.phone.trim()) return alert('Informe nome e telefone.'); await window.zap.saveDeal({ ...form, account_id: accountId, stage: 'novo' }); setForm({ title: '', phone: '', value: '', owner: '', notes: '' }); setCreating(false); await load() }

  return <div className="page-stack"><header className="page-header"><div><span className="eyebrow">CRM CONECTADO AO INBOX</span><h2>Pipeline comercial</h2><p>Leads e oportunidades com o WhatsApp sempre a um clique.</p></div><div className="header-actions"><div className="value-pill"><CircleDollarSign size={17}/><strong>{total.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong></div><button className="primary-button" onClick={() => setCreating(true)}><Plus size={16}/> Nova oportunidade</button></div></header>
    {creating && <section className="panel automation-editor" style={{ background: colors.surface, borderColor: colors.border }}><div className="form-grid"><label>Contato<input value={form.title} onChange={e => setForm({...form,title:e.target.value})} placeholder="Nome ou empresa"/></label><label>WhatsApp<input value={form.phone} onChange={e => setForm({...form,phone:e.target.value})} placeholder="5521999999999"/></label><label>Valor<input type="number" value={form.value} onChange={e => setForm({...form,value:e.target.value})}/></label><label>Responsável<input value={form.owner} onChange={e => setForm({...form,owner:e.target.value})} placeholder="Nome do atendente"/></label></div><div className="editor-actions"><button className="ghost-button" onClick={() => setCreating(false)}>Cancelar</button><button className="primary-button" onClick={create}>Criar oportunidade</button></div></section>}
    <div className="kanban-board">{stages.map((stage, stageIndex) => { const items = deals.filter(deal => deal.stage === stage.id); const value = items.reduce((sum, d) => sum + Number(d.value || 0), 0); return <section className="kanban-column" key={stage.id} style={{ background: colors.surface, borderColor: colors.border }}><header><div><strong>{stage.label}</strong><span>{items.length}</span></div><small>{value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</small></header><div className="kanban-cards">{items.map(deal => <article className="deal-card" key={deal.id}><strong>{deal.title}</strong><span>{deal.phone}</span><b>{Number(deal.value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</b>{deal.owner && <small>Responsável: {deal.owner}</small>}<div className="deal-actions"><button disabled={stageIndex === 0} onClick={() => move(deal,-1)}><ChevronLeft size={15}/></button><button onClick={() => window.zap.sendMessage(deal.phone, 'Olá! Podemos continuar seu atendimento por aqui?', accountId)}>Abrir conversa</button><button disabled={stageIndex === stages.length-1} onClick={() => move(deal,1)}><ChevronRight size={15}/></button><button className="danger" onClick={async()=>{if(confirm('Excluir oportunidade?')){await window.zap.deleteDeal(deal.id);await load()}}}><Trash2 size={14}/></button></div></article>)}</div></section>})}</div>
  </div>
}
